version: '3.6'


services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            -   ./:/app
        command: npm run start:dev
        networks:
            - app-network

networks:
    app-network: