version: '3.6'


services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            -   ./:/app
        command: npm run start:dev
        networks:
            - app-network
        environment:
            - APP_PORT=8080
        ports:
            - 8080:8080


networks:
    app-network: